# Generated by Django 4.1.7 on 2023-06-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcalAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('customer_name', models.CharField(max_length=200)),
                ('product', models.CharField(max_length=500)),
                ('total_price', models.FloatField()),
                ('customer_contact_no', models.IntegerField()),
                ('colour', models.CharField(max_length=200)),
                ('colour_code', models.IntegerField()),
                ('add_ons', models.CharField(max_length=500)),
                ('additional_notes', models.CharField(max_length=500)),
            ],
        ),
    ]
